"use client";

import Image from "next/image";
import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";

const TILES = [
  { src: "/landing/interior.jpg", tag: "Real estate", depth: -50, span: "sm:col-span-2 sm:row-span-2 aspect-[16/10]" },
  { src: "/landing/product-skincare.jpg", tag: "Product", depth: 40, span: "aspect-[3/4]" },
  { src: "/landing/food.jpg", tag: "Hospitality", depth: -30, span: "aspect-[3/4]" },
  { src: "/landing/fashion-flatlay.jpg", tag: "Fashion", depth: 50, span: "aspect-square" },
  { src: "/landing/cafe.jpg", tag: "Café", depth: -40, span: "aspect-square" },
];

function Tile({ src, tag, depth, span }: (typeof TILES)[number]) {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ["start end", "end start"] });
  const y = useTransform(scrollYProgress, [0, 1], [depth, -depth]);

  return (
    <motion.div
      ref={ref}
      style={{ y }}
      className={`group relative overflow-hidden rounded-2xl border border-white/10 ${span}`}
    >
      <Image
        src={src}
        alt={`${tag} — made with tenfold`}
        fill
        className="object-cover transition-transform duration-700 group-hover:scale-105"
        sizes="(max-width: 640px) 100vw, 33vw"
      />
      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" />
      <span className="absolute bottom-3 left-3 rounded-full border border-white/15 bg-black/40 px-3 py-1 text-xs font-medium backdrop-blur">
        {tag}
      </span>
    </motion.div>
  );
}

export function ShowcaseSection() {
  return (
    <section id="showcase" className="relative overflow-hidden px-5 py-28">
      <div className="pointer-events-none absolute left-1/2 top-1/3 -z-10 h-[500px] w-[700px] -translate-x-1/2 rounded-full bg-primary/10 blur-[150px]" />
      <div className="mx-auto max-w-6xl">
        <div className="mx-auto mb-14 max-w-2xl text-center">
          <p className="mb-3 text-sm font-medium uppercase tracking-[0.2em] text-primary">
            Made with tenfold
          </p>
          <h2 className="font-serif text-4xl font-bold tracking-tight sm:text-5xl">
            Every image here was generated by the product
          </h2>
          <p className="mt-4 text-muted-foreground">
            No stock photos. This is the actual output — from one prompt each.
          </p>
        </div>

        <div className="grid auto-rows-[180px] grid-cols-2 gap-4 sm:auto-rows-[200px] lg:grid-cols-4">
          {TILES.map((t) => (
            <Tile key={t.src} {...t} />
          ))}
        </div>
      </div>
    </section>
  );
}
